[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run build:web"]

[start]
cmd = "node web-server.js"
